export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAIL = "FETCH_CATEGORY_FAIL";
export const FETCH_CATEGORY_START = "FETCH_CATEGORY_START";
export const SET_USER_INFO = "SET_USER_INFO";